### ISSUE TITLE
新版脚本不再默认生成服务端配置，且配置文件结构完全不同

### ISSUE THREAD

**Issue by xxzou** [v2fly/fhs-install-v2ray#51]
https://www.v2ray.com/ 等网站完全按照旧版脚本介绍。而新版脚本不再默认生成服务端配置，且配置文件夹/usr/local/etc/v2ray/中默认有9个json文件：
00_log.json  02_dns.json      04_policy.json    06_outbounds.json  08_stats.json
01_api.json  03_routing.json  05_inbounds.json  07_transport.json  09_reverse.json
尝试将旧版中的“inbounds”项直接写入05_inbounds.json文件，重启服务后仍无法连接(已停止防火墙)。

请允许保留旧版脚本一段时间，直至主要教程更新。

**Comment by IceCodeNew** [comment]
旧版脚本不再保留的原因是因为它没有跟上 v2ray-core 项目版本发布的最新命名方式，而且无人愿意维护。所以恢复旧版脚本以后也是无法使用它来安装的。

**Comment by IceCodeNew** [comment]
> [v2ray.com](https://www.v2ray.com/) 等网站完全按照旧版脚本介绍。

你应该知道这个文档已经处于不再维护的状态了，现在看文档应该看 v2fly.org

**Comment by jiahaoliang** [comment]
> > [v2ray.com](https://www.v2ray.com/) 等网站完全按照旧版脚本介绍。
> 
> 你应该知道这个文档已经处于不再维护的状态了，现在看文档应该看 v2fly.org

Take [this](https://www.v2fly.org/guide/start.html#%E5%AE%A2%E6%88%B7%E7%AB%AF)  for example. Even the docs on v2fly.org are still not up-to-date. Let alone tons of third party tutorials.

I don't see the necessity for changing the config file structure entirely at current version v4.X.X. Given the orginal v2ray/v2ray project explicitly says config file should be [compatible at least one major release](https://www.v2ray.com/chapter_00/faq.html#backward-compatibility). Now that fhs-install-v2ray became the one and the only default official script, it is better following the same back-compatiblity policy with v2ray itself.

To fix it, I think just adding the same [config.json](https://github.com/v2fly/v2ray-core/blob/master/release/config/config.json) to /usr/local/etc/v2ray should be suffient for now. Given all the 00_**.json, 01_**.json, etc. are empty by default, `/usr/local/bin/v2ray -confdir /usr/local/etc/v2ray/` will still read config from default config.json as before.

To avoid future conflicts, instruct the users to delete config.json before making changes to 00_**.json, 01_**.json, etc. in docs. But I believe that should happen at version v6.X.X instead of now.

**Comment by allury** [comment]
> > > [v2ray.com](https://www.v2ray.com/)等网站完全按照旧版脚本介绍。
> > 
> > 
> > 你应该知道这个文档已经处于不再维护的状态了，现在看文档应该看v2fly.org
> 
> 以[这个](https://www.v2fly.org/guide/start.html#%E5%AE%A2%E6%88%B7%E7%AB%AF) 为例。甚至v2fly.org上的文档都还不是最新的。更不用说大量的第三方教程了。
> 
> 我不认为有必要在当前版本v4.XX上完全更改配置文件的结构，因为原始的v2ray / v2ray项目明确表示配置文件应[至少兼容一个主要版本](https://www.v2ray.com/chapter_00/faq.html#backward-compatibility)。既然fhs-install-v2ray成为了一个也是唯一的默认正式脚本，那么最好还是对v2ray本身遵循相同的向后兼容策略。
> 
> 要解决此问题，我认为现在只需将相同的[config.json](https://github.com/v2fly/v2ray-core/blob/master/release/config/config.json)添加到/ usr / local / etc / v2ray即可。鉴于所有00 _ **。json，01 _ **。json等默认情况下均为空，`/usr/local/bin/v2ray -confdir /usr/local/etc/v2ray/`因此仍将像以前一样从默认config.json中读取配置。
> 
> 为了避免将来发生冲突，请指示用户在对文档中的00 _ **。json，01 _ **。json等进行更改之前删除config.json。但是我认为应该在v6.XX版本而不是现在发生。

同意
