### ISSUE TITLE
stuck at the final step: # v2ray --config=/usr/local/etc/v2ray/config.json

### ISSUE THREAD

**Issue by yingjiewei** [v2fly/fhs-install-v2ray#78]
Hi developer:
    Currently, I follow all the steps on the instructions and using v2ray 4.27.5 in centos7. When I run:
 [root@nice-silo-1 ~]# v2ray --config=/usr/local/etc/v2ray/config.json
I got:
>>>
V2Ray 4.27.5 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.7 linux/amd64)
A unified platform for anti-censorship.
2020/09/02 21:38:59 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /usr/local/etc/v2ray/config.json
2020/09/02 21:38:59 [Warning] v2ray.com/core: V2Ray 4.27.5 started
[cursor on here]
>>>
and the cursor is always on and at the final line, resulting in v2ray service not starting.

**Comment by IceCodeNew** [comment]
This is not a bug, and the program is not stuck.
It is because you made the program running in the foreground, as is has nothing to do with user input, it will keep running and processing the network traffic in the foreground.
If you are using this project to install v2ray, you should consider using `systemd` to manage v2ray service rather than manually commanding in a shell to start v2ray.
